config/routes.rb
NestedSetApp::Application.routes.draw do

  root 'welcome#index'
  resources :categories, :products, :catalogs

end

app/models/catalog.rb
class Catalog < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
  acts_as_nested_set

  has_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/catalogs_controller.rb
class CatalogsController < ApplicationController

  def index

    @catalogs = Catalog.all
    respond_to do |format|
      format.html
      format.json { render 'index.rabl', status: :ok}

    end


  end

  def new

  end

  def create
    @catalog = Catalog.new(catalog_params)
    @catalog.save!
  end

  def show

  end

  def catalog_params
    params[:catalog].permit(:name)
  end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
    @products = Product.all

    respond_to do |format|
      format.html
      format.json { render 'index.rabl', status: :ok}
    end

  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params[:category].permit(:name, :parent_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :category_id, :price)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @categories = Category.order(lft: :asc, name: :asc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def ac(path)
    'active' if current_page?(path)
  end

  def tree_select(nested_set)

  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper

  def nested_li(objects, &block)
    objects = objects.order(:lft) if objects.is_a? Class

    return '' if objects.size == 0

    output = '<ul><li>'
    path = [nil]

    objects.each_with_index do |o, i|
      if o.parent_id != path.last
        if path.include?(o.parent_id)
          while path.last != o.parent_id
            path.pop
            output << '</li></ul>'
          end
          output << '</li><li>'
        else
          path << o.parent_id
          output << '<ul><li>'
        end
      elsif i != 0
        output << '</li><li>'
      end
      output << capture(o, path.size - 1, &block)
    end

    output << '</li></ul>' * path.length
    output.html_safe
  end

end

app/views/catalogs/index.html.haml
- content_for :head do
  = javascript_include_tag 'catalogs/catalogs'

#app-container

app/views/categories/_form.html.haml
= semantic_form_for @category do |f|
  = f.inputs
  = f.actions

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
%h1 Listing categories

%table.table
  %tr
    %th Name
    %th Parent ID
    %th

  - @categories.each do |category|
    %tr
      %td=category.name
      %td=category.parent_id
      %td
        = link_to 'Show', category
        = link_to 'Edit', edit_category_path(category)
        = link_to 'Destroy', category, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Category', new_category_path

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_category_path(@category)
\|
= link_to 'Back', categories_path

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default
  = link_to 'Nested Set App', root_path, class: 'navbar-brand'
  %ul.nav.navbar-nav
    %li{class: ac(categories_path)}=link_to 'Categories', categories_path
    %li{class: ac(products_path)}=link_to 'Products', products_path
    %li{class: ac(catalogs_path)}=link_to 'Catalogs', catalogs_path, {data: {no_turbolink: ''}}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title NestedSetApp
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    = yield(:head)
  %body
    .container
      = render 'layouts/navigation'
      = yield

app/views/products/_form.html.haml
= semantic_form_for @product do |f|
  = f.inputs
  = f.actions

app/views/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', @product
\|
= link_to 'Back', products_path

app/views/products/index.html.haml
%h1 Listing products

%table
  %tr
    %th Name
    %th Category
    %th Price
    %th
    %th
    %th

  - @products.each do |product|
    %tr
      %td= product.name
      %td= product.category
      %td= product.price
      %td= link_to 'Show', product
      %td= link_to 'Edit', edit_product_path(product)
      %td= link_to 'Destroy', product, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Product', new_product_path

app/views/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', products_path

app/views/products/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @product.name
%p
  %b Category:
  = @product.category
%p
  %b Price:
  = @product.price

= link_to 'Edit', edit_product_path(@product)
\|
= link_to 'Back', products_path

app/views/welcome/index.html.haml
%h1 Examples
.well
  %h4 Nested view with ul/li
  %ul
  = nested_li(@categories) do |c|
    =c.name


.well
  %h4 Select box with tree hierarchy
  %form.form-horizontal
    .form-group
      =select_tag "categories", options_from_collection_for_select(@categories, "id", "name"), class: 'form-control'
    .form-group
      =select_tag "categories_2", options_from_collection_for_select(@categories, "id", "name"), class: 'form-control'